### ISSUE TITLE
Question about the result in paper?

### ISSUE THREAD

**Issue by PeemapatW** [Tixierae/graph_2D_CNN#1]
Hi,
I have a question about runtime result that mention in your paper. Does it include the runtime of graph embedding method (node2vec).

**Comment by Tixierae** [comment]
Hi. The reported runtime is the time per epoch of the CNN model - it doesn't include the time required to get the node embeddings. Note that node2vec is supposed to be implementable in linear time w.r.t. the size of the graphs.
